#SPDX-License-Identifier: MIT-0
---
# defaults file for kvm_provision
base_image_name: Fedora-Cloud-Base-Generic-42-1.1.x86_64.qcow2 
base_image_url: https://mirror.karneval.cz/pub/linux/fedora/linux/releases/42/Cloud/x86_64/images/{{ base_image_name }}
base_image_sha: e401a4db2e5e04d1967b6729774faa96da629bcf3ba90b67d8d9cce9906bec0f
libvirt_pool_dir: "/var/lib/libvirt/images"
vm_name: f34-dev
vm_vcpus: 2
vm_ram_mb: 2048
vm_net: default
vm_root_pass: test123
cleanup_tmp: no
ssh_key: /root/.ssh/id_rsa.pub
